package Classes;

import java.awt.Image;
import java.util.Date;
import java.util.Locale;
import javax.swing.ImageIcon;
import org.ocpsoft.prettytime.PrettyTime;

/**
 *
 * @author Pedro
 */
public class Comment extends javax.swing.JPanel {

    private String userThatSent;
    private int friendsInCommon;
    
    private int postID;
    
    /**
     * Creates new form Post
     */
    public Comment() {
        initComponents();
    }

    public Comment(ImageIcon senderProfilePic, String userThatSent, Date commentDate, String comment) {
        initComponents();
        this.userThatSent = userThatSent;
        changeLabels(userThatSent, commentDate, comment);
        ProfilePicture.setIcon(processImage(senderProfilePic, 60, 60));
    }
    
    private String processDate(Date date){
        PrettyTime p = new PrettyTime(new Locale("es"));
        return p.format(date);
    }
    
    private ImageIcon processImage(ImageIcon image, int width, int height){
        return new ImageIcon(image.getImage().getScaledInstance(width, height, Image.SCALE_FAST));
    }
    
    private void changeLabels(String sender, Date date, String comment){
        Name.setText(sender);
        CommentDate.setText(processDate(date));
        CommentContent.setText("<html>" + comment + "</html>");
    }

    public String getUserThatSent() {
        return userThatSent;
    }

    public void setUserThatSent(String userThatSent) {
        this.userThatSent = userThatSent;
    }

    public int getFriendsInCommon() {
        return friendsInCommon;
    }

    public void setFriendsInCommon(int friendsInCommon) {
        this.friendsInCommon = friendsInCommon;
    }
    
    public String getUserThatPosted() {
        return userThatSent;
    }

    public void setUserThatPosted(String userThatPosted) {
        this.userThatSent = userThatPosted;
    }

    public int getPostID() {
        return postID;
    }

    public void setPostID(int postID) {
        this.postID = postID;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name = new javax.swing.JLabel();
        CommentDate = new javax.swing.JLabel();
        ProfilePicture = new javax.swing.JLabel();
        CommentContent = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(38, 37, 37)));
        setForeground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(596, 170));
        setMinimumSize(new java.awt.Dimension(596, 170));
        setPreferredSize(new java.awt.Dimension(596, 170));

        Name.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("<html>Person Name<html>");
        Name.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        CommentDate.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        CommentDate.setForeground(new java.awt.Color(204, 204, 204));
        CommentDate.setText("hace AAAAA días");
        CommentDate.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        ProfilePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DEFAULT_PROFILE_PICTURE_SMALL.png"))); // NOI18N

        CommentContent.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        CommentContent.setForeground(new java.awt.Color(255, 255, 255));
        CommentContent.setText("<html> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </html>");
        CommentContent.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CommentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(CommentContent, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CommentDate))
                    .addComponent(ProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CommentContent, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CommentContent;
    private javax.swing.JLabel CommentDate;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel ProfilePicture;
    // End of variables declaration//GEN-END:variables
}
