package Classes;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Pedro
 */
public class FriendRequest extends javax.swing.JPanel {

    private String userThatSent;
    private int friendsInCommon;

    private String personID;

    /**
     * Creates new form Post
     */
    public FriendRequest() {
        initComponents();
    }

    public FriendRequest(ImageIcon senderProfilePic, String userThatSent, int friendsInCommon) {
        initComponents();
        this.userThatSent = userThatSent;
        changeLabels(userThatSent, friendsInCommon);
        ProfilePicture.setIcon(processImage(senderProfilePic, 206, 215));
    }

    private ImageIcon processImage(ImageIcon image, int width, int height) {
        return new ImageIcon(image.getImage().getScaledInstance(width, height, Image.SCALE_FAST));
    }

    private void changeLabels(String sender, int friendsInCommon) {
        Name.setText(sender);
        FriendsInCommon.setText("<html> " + friendsInCommon + " amigos en común </html>");
    }

    public String getUserThatSent() {
        return userThatSent;
    }

    public void setUserThatSent(String userThatSent) {
        this.userThatSent = userThatSent;
    }

    public int getFriendsInCommon() {
        return friendsInCommon;
    }

    public void setFriendsInCommon(int friendsInCommon) {
        this.friendsInCommon = friendsInCommon;
    }

    public String getUserThatPosted() {
        return userThatSent;
    }

    public void setUserThatPosted(String userThatPosted) {
        this.userThatSent = userThatPosted;
    }

    public String getPostID() {
        return personID;
    }

    public void setPostID(String postID) {
        this.personID = postID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProfilePicture = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        FriendsInCommon = new javax.swing.JLabel();
        AcceptFriendRequest = new javax.swing.JButton();
        RejectFriendRequest = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(38, 37, 37)));
        setForeground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(220, 380));
        setMinimumSize(new java.awt.Dimension(220, 380));
        setPreferredSize(new java.awt.Dimension(220, 380));

        ProfilePicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfilePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DEFAULT_POST_IMAGE.png"))); // NOI18N
        ProfilePicture.setAlignmentX(0.5F);
        ProfilePicture.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ProfilePicture.setMaximumSize(new java.awt.Dimension(206, 215));
        ProfilePicture.setMinimumSize(new java.awt.Dimension(206, 215));
        ProfilePicture.setPreferredSize(new java.awt.Dimension(206, 215));

        Name.setFont(new java.awt.Font("Leelawadee", 1, 20)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("<html>Person Name<html>");
        Name.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        FriendsInCommon.setFont(new java.awt.Font("Leelawadee", 0, 16)); // NOI18N
        FriendsInCommon.setForeground(new java.awt.Color(204, 204, 204));
        FriendsInCommon.setText("#### amigos en común");
        FriendsInCommon.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        AcceptFriendRequest.setBackground(new java.awt.Color(0, 153, 51));
        AcceptFriendRequest.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        AcceptFriendRequest.setForeground(new java.awt.Color(255, 255, 255));
        AcceptFriendRequest.setText("Aceptar");
        AcceptFriendRequest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AcceptFriendRequest.setContentAreaFilled(false);
        AcceptFriendRequest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AcceptFriendRequest.setHideActionText(true);
        AcceptFriendRequest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AcceptFriendRequest.setIconTextGap(15);
        AcceptFriendRequest.setOpaque(true);
        AcceptFriendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptFriendRequestActionPerformed(evt);
            }
        });

        RejectFriendRequest.setBackground(new java.awt.Color(73, 73, 73));
        RejectFriendRequest.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        RejectFriendRequest.setForeground(new java.awt.Color(255, 255, 255));
        RejectFriendRequest.setText("Rechazar");
        RejectFriendRequest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RejectFriendRequest.setContentAreaFilled(false);
        RejectFriendRequest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RejectFriendRequest.setHideActionText(true);
        RejectFriendRequest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RejectFriendRequest.setIconTextGap(15);
        RejectFriendRequest.setOpaque(true);
        RejectFriendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectFriendRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name)
                    .addComponent(FriendsInCommon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AcceptFriendRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RejectFriendRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(ProfilePicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(FriendsInCommon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AcceptFriendRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RejectFriendRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptFriendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptFriendRequestActionPerformed
        /*
            ELIMINAR RELACIÓN [:WANTS_TO_FRIEND] Y CREAR IS_FRIENDS
         */
        BinaryDiary.refreshFriendRequests();
    }//GEN-LAST:event_AcceptFriendRequestActionPerformed

    private void RejectFriendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectFriendRequestActionPerformed
        /*
            ELIMINAR RELACIÓN [:WANTS_TO_FRIEND] Y CREAR IS_FRIENDS
         */
    }//GEN-LAST:event_RejectFriendRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptFriendRequest;
    private javax.swing.JLabel FriendsInCommon;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel ProfilePicture;
    private javax.swing.JButton RejectFriendRequest;
    // End of variables declaration//GEN-END:variables
}
