package Classes;

import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JToolBar.Separator;
import org.neo4j.driver.Result;

/**
 *
 * @author Pedro
 */
public class LoginPanel extends javax.swing.JPanel {
    
    private ImageIcon POST_IMAGE_TO_SAVE;
    
    public LoginPanel(){
        initComponents(); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateAccountDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        MiniSignUpPanel = new javax.swing.JPanel();
        EmailSignUp = new javax.swing.JTextField();
        PasswordLogin1 = new javax.swing.JPasswordField();
        SignUpButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        NameSignUp = new javax.swing.JTextField();
        LastNameSignUp = new javax.swing.JTextField();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        LogoLabel2 = new javax.swing.JLabel();
        LogoLabel3 = new javax.swing.JLabel();
        MiniLoginPanel = new javax.swing.JPanel();
        EmailLogin = new javax.swing.JTextField();
        PasswordLogin = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        CreateAccountButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        LogoLabel = new javax.swing.JLabel();
        LogoLabel1 = new javax.swing.JLabel();

        CreateAccountDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        CreateAccountDialog.setTitle("Registrarse");
        CreateAccountDialog.setModal(true);
        CreateAccountDialog.setResizable(false);
        CreateAccountDialog.setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(206, 206, 206));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        MiniSignUpPanel.setBackground(new java.awt.Color(255, 255, 255));
        MiniSignUpPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        MiniSignUpPanel.setMaximumSize(new java.awt.Dimension(1081, 133));
        MiniSignUpPanel.setMinimumSize(new java.awt.Dimension(1081, 133));

        EmailSignUp.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        EmailSignUp.setText("Correo Electrónico");
        EmailSignUp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.gray, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        PasswordLogin1.setFont(PasswordLogin1.getFont().deriveFont(PasswordLogin1.getFont().getStyle() | java.awt.Font.BOLD, PasswordLogin1.getFont().getSize()+8));
        PasswordLogin1.setText("Contraseña");
        PasswordLogin1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.gray, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        SignUpButton.setBackground(new java.awt.Color(8, 169, 182));
        SignUpButton.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(255, 255, 255));
        SignUpButton.setText("Registrarse");
        SignUpButton.setBorder(null);
        SignUpButton.setContentAreaFilled(false);
        SignUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUpButton.setHideActionText(true);
        SignUpButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SignUpButton.setIconTextGap(15);
        SignUpButton.setOpaque(true);
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

        NameSignUp.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        NameSignUp.setText("Nombre");
        NameSignUp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.gray, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        LastNameSignUp.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        LastNameSignUp.setText("Apellido");
        LastNameSignUp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.gray, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout MiniSignUpPanelLayout = new javax.swing.GroupLayout(MiniSignUpPanel);
        MiniSignUpPanel.setLayout(MiniSignUpPanelLayout);
        MiniSignUpPanelLayout.setHorizontalGroup(
            MiniSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniSignUpPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(MiniSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MiniSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(MiniSignUpPanelLayout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator2)
                        .addComponent(EmailSignUp)
                        .addComponent(PasswordLogin1)
                        .addGroup(MiniSignUpPanelLayout.createSequentialGroup()
                            .addComponent(NameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LastNameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(658, Short.MAX_VALUE))
        );
        MiniSignUpPanelLayout.setVerticalGroup(
            MiniSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiniSignUpPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(MiniSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel1.add(MiniSignUpPanel);
        MiniSignUpPanel.setBounds(660, 70, 463, 550);

        LogoLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGO_TEXT_LARGE.png"))); // NOI18N
        jPanel1.add(LogoLabel2);
        LogoLabel2.setBounds(10, 350, 650, 210);

        LogoLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BIG_LOGO.png"))); // NOI18N
        jPanel1.add(LogoLabel3);
        LogoLabel3.setBounds(30, 90, 350, 340);

        javax.swing.GroupLayout CreateAccountDialogLayout = new javax.swing.GroupLayout(CreateAccountDialog.getContentPane());
        CreateAccountDialog.getContentPane().setLayout(CreateAccountDialogLayout);
        CreateAccountDialogLayout.setHorizontalGroup(
            CreateAccountDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1184, Short.MAX_VALUE)
            .addGroup(CreateAccountDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CreateAccountDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        CreateAccountDialogLayout.setVerticalGroup(
            CreateAccountDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
            .addGroup(CreateAccountDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CreateAccountDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setBackground(new java.awt.Color(206, 206, 206));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setForeground(new java.awt.Color(51, 51, 51));
        setLayout(null);

        MiniLoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        MiniLoginPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        MiniLoginPanel.setMaximumSize(new java.awt.Dimension(1081, 133));
        MiniLoginPanel.setMinimumSize(new java.awt.Dimension(1081, 133));

        EmailLogin.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        EmailLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.gray, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        PasswordLogin.setFont(PasswordLogin.getFont().deriveFont(PasswordLogin.getFont().getStyle() | java.awt.Font.BOLD, PasswordLogin.getFont().getSize()+8));
        PasswordLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.gray, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        LoginButton.setBackground(new java.awt.Color(0, 153, 51));
        LoginButton.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Iniciar Sesión");
        LoginButton.setBorder(null);
        LoginButton.setContentAreaFilled(false);
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.setHideActionText(true);
        LoginButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LoginButton.setIconTextGap(15);
        LoginButton.setOpaque(true);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        CreateAccountButton.setBackground(new java.awt.Color(8, 169, 182));
        CreateAccountButton.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        CreateAccountButton.setForeground(new java.awt.Color(255, 255, 255));
        CreateAccountButton.setText("Crear Cuenta");
        CreateAccountButton.setBorder(null);
        CreateAccountButton.setContentAreaFilled(false);
        CreateAccountButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CreateAccountButton.setHideActionText(true);
        CreateAccountButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CreateAccountButton.setIconTextGap(15);
        CreateAccountButton.setOpaque(true);
        CreateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountButtonActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout MiniLoginPanelLayout = new javax.swing.GroupLayout(MiniLoginPanel);
        MiniLoginPanel.setLayout(MiniLoginPanelLayout);
        MiniLoginPanelLayout.setHorizontalGroup(
            MiniLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniLoginPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(MiniLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LoginButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmailLogin)
                    .addComponent(PasswordLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MiniLoginPanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(CreateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MiniLoginPanelLayout.setVerticalGroup(
            MiniLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiniLoginPanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(EmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        add(MiniLoginPanel);
        MiniLoginPanel.setBounds(660, 130, 463, 334);

        LogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGO_TEXT_LARGE.png"))); // NOI18N
        add(LogoLabel);
        LogoLabel.setBounds(10, 350, 650, 210);

        LogoLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BIG_LOGO.png"))); // NOI18N
        add(LogoLabel1);
        LogoLabel1.setBounds(30, 90, 350, 340);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        /*
            LOGIN TIENE QUE CAMBIAR Y ACTUALIZAR ACTIVE USER
        */
         try{
         Result result = BinaryDiary.database.QueryExecutor("match(u:usuario) where (u.Email='"+EmailLogin.getText()+"') return u.Contraseña,u.Nombre,u.Foto_Perfil,u.Foto_Portada");
         org.neo4j.driver.Record r = result.next();
         System.out.println(r);
         System.out.println(r.get("u.Contraseña"));
         String s = "\""+PasswordLogin.getText()+"\"";
         String f = r.get("u.Contraseña").toString();
         String imagen_perfil= r.get("u.Nombre").toString().replace("\"","");
         
        if(f.equals(s)){
             
             BinaryDiary.userEmail=EmailLogin.getText();
             BinaryDiary.name=r.get("u.Nombre").toString().replace("\"","");
             System.out.println(BinaryDiary.name);
             JOptionPane.showMessageDialog(null,"Bienvenido! "+BinaryDiary.name);
             BinaryDiary.login(BinaryDiary.name , BinaryDiary.userEmail, new ImageIcon(imagen_perfil));
            EmailLogin.setText("");
            PasswordLogin.setText("");
            
            
         }else{
             JOptionPane.showMessageDialog(null,"Usuario o Contraseña incorrectos");
              PasswordLogin.setText("");
         }
        }catch(Exception e){
             JOptionPane.showMessageDialog(null,"Usuario o Contraseña incorrectos Hola");
             System.out.println(e);
             }
        // IF SUCCESSFUL LOGIN
        
    }//GEN-LAST:event_LoginButtonActionPerformed

    private boolean emailValidator(String input){
        final String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                                   + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        return input.matches(EMAIL_PATTERN);
    }
    
    private void CreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountButtonActionPerformed
        // hola
        this.CreateAccountDialog.pack();
        this.CreateAccountDialog.setLocationRelativeTo(null);
        this.CreateAccountDialog.setVisible(true);
    }//GEN-LAST:event_CreateAccountButtonActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        // SU CODIGO AQUI
     String nombre ="";
     String apellido ="";
     String contraseña ="";
     String email ="";
     
     SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
     try{
     nombre=NameSignUp.getText();
     apellido =LastNameSignUp.getText();
     contraseña=PasswordLogin1.getText();
     email=EmailSignUp.getText();
     
     Result result=BinaryDiary.database.QueryExecutor("match(u:usuario) where (u.Email='"+email+"') return u");
      ArrayList<Object> myList = new ArrayList<>();
        
        while(result.hasNext()) {
              org.neo4j.driver.Record r = result.next();
              
            myList.add(r.get("Nombre"));
        }
         System.out.println("Antes del if de mylist");
        if(myList.isEmpty()){
           result=BinaryDiary.database.QueryExecutor("create (:usuario{Email:'"+email+"',Nombre:'"+nombre+"',Apellido:'"+apellido+"',Contraseña:'"
                  +contraseña+"',Nacimiento: date('"+formatter.format(jCalendar1.getDate()).toString()+"'),Foto_Perfil:'./ASSETS/DEFAULT_PROFILE_PICTURE_SMALL',"
                          + "Foto_Portada:'./ASSETS/DEFAULT_PROFILE_PICTURE_BIG',Datos_Personales:'Escriba algo aquí'})");
          myList.clear();
          
          JOptionPane.showMessageDialog(null,"Usuario Registrado Exitosamente");
          NameSignUp.setText("");
          LastNameSignUp.setText("");
          CreateAccountDialog.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Este correo ya ha sido registrado");
        
        }
         System.out.println("Después del if");
     }catch(Exception e){
         
     }
    }//GEN-LAST:event_SignUpButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateAccountButton;
    private javax.swing.JDialog CreateAccountDialog;
    private javax.swing.JTextField EmailLogin;
    private javax.swing.JTextField EmailSignUp;
    private javax.swing.JTextField LastNameSignUp;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JLabel LogoLabel1;
    private javax.swing.JLabel LogoLabel2;
    private javax.swing.JLabel LogoLabel3;
    private javax.swing.JPanel MiniLoginPanel;
    private javax.swing.JPanel MiniSignUpPanel;
    private javax.swing.JTextField NameSignUp;
    private javax.swing.JPasswordField PasswordLogin;
    private javax.swing.JPasswordField PasswordLogin1;
    private javax.swing.JButton SignUpButton;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
