package Classes;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Pedro
 */
public class PersonResult extends javax.swing.JPanel {

    private String userThatSent;
    private int friendsInCommon;
    
    private String personID;
    
    /**
     * Creates new form Post
     */
    public PersonResult() {
        initComponents();
    }

    public PersonResult(ImageIcon senderProfilePic, String userThatSent, int friendsInCommon, boolean alreadySent,String UserThatSendEmail) {
        initComponents();
        this.userThatSent = userThatSent;
        this.personID=UserThatSendEmail;
        changeLabels(userThatSent, friendsInCommon);
        ProfilePicture.setIcon(processImage(senderProfilePic, 206, 215));
        this.SendFriendRequest.setEnabled(!alreadySent);
        if(alreadySent) {
            SendFriendRequest.setText("Enviado");
            SendFriendRequest.setForeground(Color.BLACK);
            SendFriendRequest.setBackground(new Color(102,102,102));
            SendFriendRequest.setBorder(null);
        }
    }
    
    private ImageIcon processImage(ImageIcon image, int width, int height){
        return new ImageIcon(image.getImage().getScaledInstance(width, height, Image.SCALE_FAST));
    }
    
    private void changeLabels(String sender, int friendsInCommon){
        Name.setText(sender);
        FriendsInCommon.setText("<html> " + friendsInCommon + " amigos en común </html>");
    }

    public String getUserThatSent() {
        return userThatSent;
    }

    public void setUserThatSent(String userThatSent) {
        this.userThatSent = userThatSent;
    }

    public int getFriendsInCommon() {
        return friendsInCommon;
    }

    public void setFriendsInCommon(int friendsInCommon) {
        this.friendsInCommon = friendsInCommon;
    }
    
    public String getUserThatPosted() {
        return userThatSent;
    }

    public void setUserThatPosted(String userThatPosted) {
        this.userThatSent = userThatPosted;
    }

    public String getPostID() {
        return personID;
    }

    public void setPostID(String postID) {
        this.personID = postID;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProfilePicture = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        FriendsInCommon = new javax.swing.JLabel();
        SendFriendRequest = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(38, 37, 37)));
        setForeground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(220, 330));
        setMinimumSize(new java.awt.Dimension(220, 330));
        setPreferredSize(new java.awt.Dimension(220, 330));

        ProfilePicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfilePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DEFAULT_POST_IMAGE.png"))); // NOI18N
        ProfilePicture.setAlignmentX(0.5F);
        ProfilePicture.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ProfilePicture.setMaximumSize(new java.awt.Dimension(206, 215));
        ProfilePicture.setMinimumSize(new java.awt.Dimension(206, 215));
        ProfilePicture.setPreferredSize(new java.awt.Dimension(206, 215));

        Name.setFont(new java.awt.Font("Leelawadee", 1, 20)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("<html>Person Name<html>");
        Name.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        FriendsInCommon.setFont(new java.awt.Font("Leelawadee", 0, 16)); // NOI18N
        FriendsInCommon.setForeground(new java.awt.Color(204, 204, 204));
        FriendsInCommon.setText("#### amigos en común");
        FriendsInCommon.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        SendFriendRequest.setBackground(new java.awt.Color(0, 153, 51));
        SendFriendRequest.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        SendFriendRequest.setForeground(new java.awt.Color(255, 255, 255));
        SendFriendRequest.setText("Enviar Solicitud");
        SendFriendRequest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SendFriendRequest.setContentAreaFilled(false);
        SendFriendRequest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SendFriendRequest.setHideActionText(true);
        SendFriendRequest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SendFriendRequest.setIconTextGap(15);
        SendFriendRequest.setOpaque(true);
        SendFriendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendFriendRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name)
                    .addComponent(FriendsInCommon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SendFriendRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(ProfilePicture, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(FriendsInCommon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SendFriendRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SendFriendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendFriendRequestActionPerformed
        BinaryDiary.sendFriendRequest("EJEMPLO", "EJEMPLO");
    }//GEN-LAST:event_SendFriendRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FriendsInCommon;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel ProfilePicture;
    private javax.swing.JButton SendFriendRequest;
    // End of variables declaration//GEN-END:variables
}
