package Classes;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Pedro
 */
public class ProfilePanel extends javax.swing.JPanel {
    
    
    private String aboutMe;
    private String fullName;
    private ImageIcon coverPhoto;
    private ImageIcon profilePicture;
    
    private String accountEmail;
    private ImageIcon COVER_PHOTO_TO_SAVE;
    private ImageIcon PROFILE_PHOTO_TO_SAVE;
    
    /**
     * Creates new form ProfilePanel
     */
    public ProfilePanel() {
        initComponents();
    }

    public ProfilePanel(String firstName, String lastName, String aboutMe, ImageIcon coverPhoto, ImageIcon profilePicture, int friendsInCommon, int postsMade) {
        initComponents();
        this.aboutMe = aboutMe;
        this.coverPhoto = coverPhoto;
        this.profilePicture = profilePicture;
        this.fullName = firstName + " " + lastName;
        changeLabels(fullName, aboutMe, friendsInCommon, postsMade);
        ProfilePicture.setIcon(processImage(profilePicture, 300, 300));
        ProfileBackground.setIcon(processImage(coverPhoto, 1160, 359));
    }

    private void changeLabels(String fullName, String aboutMe, int friendsInCommon, int postsMade){
        this.FriendCounterLabel.setText(friendsInCommon + " amigos");
        this.PostsCounter.setText(postsMade + " publicaciones");
        this.AboutMe.setText("<html>" + aboutMe + "</html>");
        this.NameLabel.setText(fullName);
    }
    
    private ImageIcon processImage(ImageIcon image, int width, int height){
        ImageIcon imageIcon = new ImageIcon(image.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH));
        return imageIcon;
    }
    
    public String getAboutMe() {
        return aboutMe;
    }

    public void setAboutMe(String aboutMe) {
        this.aboutMe = aboutMe;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public ImageIcon getCoverPhoto() {
        return coverPhoto;
    }

    public void setCoverPhoto(ImageIcon coverPhoto) {
        this.coverPhoto = coverPhoto;
    }

    public ImageIcon getProfilePicture() {
        return profilePicture;
    }

    public void setProfilePicture(ImageIcon profilePicture) {
        this.profilePicture = profilePicture;
    }

    public String getAccountEmail() {
        return accountEmail;
    }

    public void setAccountEmail(String accountEmail) {
        this.accountEmail = accountEmail;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditProfile = new javax.swing.JDialog();
        EditProfilePanel = new javax.swing.JPanel();
        Exit = new javax.swing.JButton();
        ProfilePictureEdit = new javax.swing.JLabel();
        ProfileBackgroundEdit = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AboutMeEdit = new javax.swing.JTextArea();
        ConfirmChanges = new javax.swing.JButton();
        Label = new javax.swing.JLabel();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        EditProfileButton = new javax.swing.JButton();
        ProfilePicture = new javax.swing.JLabel();
        ProfileBackground = new javax.swing.JLabel();
        AboutMe = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        FriendCounterLabel = new javax.swing.JLabel();
        PostsCounter = new javax.swing.JLabel();

        EditProfile.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        EditProfile.setTitle("Editar Perfil");
        EditProfile.setMinimumSize(new java.awt.Dimension(1148, 740));
        EditProfile.setResizable(false);
        EditProfile.setSize(new java.awt.Dimension(1148, 740));
        EditProfile.getContentPane().setLayout(null);

        EditProfilePanel.setBackground(new java.awt.Color(51, 51, 51));
        EditProfilePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        EditProfilePanel.setPreferredSize(new java.awt.Dimension(1148, 707));
        EditProfilePanel.setLayout(null);

        Exit.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CLOSE_BUTTON_SMALL.png"))); // NOI18N
        Exit.setBorder(null);
        Exit.setBorderPainted(false);
        Exit.setContentAreaFilled(false);
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        Exit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Exit.setIconTextGap(15);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        EditProfilePanel.add(Exit);
        Exit.setBounds(1070, 10, 60, 60);

        ProfilePictureEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfilePictureEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DEFAULT_PROFILE_PICTURE_BIG.png"))); // NOI18N
        ProfilePictureEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProfilePictureEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfilePictureEditMouseClicked(evt);
            }
        });
        EditProfilePanel.add(ProfilePictureEdit);
        ProfilePictureEdit.setBounds(490, 20, 170, 170);

        ProfileBackgroundEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfileBackgroundEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RobloxScreenShot20180712_191040726.png"))); // NOI18N
        ProfileBackgroundEdit.setAlignmentX(0.5F);
        ProfileBackgroundEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProfileBackgroundEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileBackgroundEditMouseClicked(evt);
            }
        });
        EditProfilePanel.add(ProfileBackgroundEdit);
        ProfileBackgroundEdit.setBounds(330, 230, 510, 220);

        AboutMeEdit.setColumns(20);
        AboutMeEdit.setRows(5);
        jScrollPane1.setViewportView(AboutMeEdit);

        EditProfilePanel.add(jScrollPane1);
        jScrollPane1.setBounds(80, 510, 1030, 110);

        ConfirmChanges.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        ConfirmChanges.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmChanges.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ACCEPT_BUTTON_SMALL.png"))); // NOI18N
        ConfirmChanges.setBorder(null);
        ConfirmChanges.setBorderPainted(false);
        ConfirmChanges.setContentAreaFilled(false);
        ConfirmChanges.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConfirmChanges.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        ConfirmChanges.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ConfirmChanges.setIconTextGap(15);
        ConfirmChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmChangesActionPerformed(evt);
            }
        });
        EditProfilePanel.add(ConfirmChanges);
        ConfirmChanges.setBounds(1060, 630, 60, 60);

        Label.setBackground(new java.awt.Color(102, 102, 102));
        Label.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        Label.setForeground(new java.awt.Color(204, 204, 204));
        Label.setText("Presentación");
        EditProfilePanel.add(Label);
        Label.setBounds(10, 460, 460, 30);

        Label1.setBackground(new java.awt.Color(102, 102, 102));
        Label1.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        Label1.setForeground(new java.awt.Color(204, 204, 204));
        Label1.setText("Foto de Perfil");
        EditProfilePanel.add(Label1);
        Label1.setBounds(10, 10, 460, 30);

        Label2.setBackground(new java.awt.Color(102, 102, 102));
        Label2.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        Label2.setForeground(new java.awt.Color(204, 204, 204));
        Label2.setText("Foto de Portada");
        EditProfilePanel.add(Label2);
        Label2.setBounds(10, 190, 460, 30);

        EditProfile.getContentPane().add(EditProfilePanel);
        EditProfilePanel.setBounds(0, 0, 1148, 707);

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(1148, 707));
        setLayout(null);

        EditProfileButton.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        EditProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        EditProfileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EDIT_PROFILE_SMALL_ICON.png"))); // NOI18N
        EditProfileButton.setBorder(null);
        EditProfileButton.setBorderPainted(false);
        EditProfileButton.setContentAreaFilled(false);
        EditProfileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditProfileButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        EditProfileButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        EditProfileButton.setIconTextGap(15);
        EditProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileButtonActionPerformed(evt);
            }
        });
        add(EditProfileButton);
        EditProfileButton.setBounds(1060, 370, 60, 60);

        ProfilePicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfilePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DEFAULT_PROFILE_PICTURE_BIG.png"))); // NOI18N
        ProfilePicture.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0), new java.awt.Color(36, 36, 36)));
        add(ProfilePicture);
        ProfilePicture.setBounds(10, 220, 300, 300);

        ProfileBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfileBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RobloxScreenShot20180712_191040726.png"))); // NOI18N
        ProfileBackground.setAlignmentX(0.5F);
        add(ProfileBackground);
        ProfileBackground.setBounds(0, 0, 1160, 359);

        AboutMe.setBackground(new java.awt.Color(102, 102, 102));
        AboutMe.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        AboutMe.setForeground(new java.awt.Color(204, 204, 204));
        AboutMe.setText("<html> Como Me Lele , Como Me Lele , Como Me Lele To Mele El Pilin  Como Me Lele , Como Me Lele , Como Me Lele To Mele El Pilin  Que Te Saquen A Pasear Que Te Saquen A Bailar Que Te Saquen A Pasear Que Te Saquen A Bailar  Como Me Lele , Como Me Lele , Como Me Lele To Mele El Pilin  aaaaa Como Me Lele , Como Me Lele , Como Me Lele To Mele El Pilin  Como Me Lele , Como Me Lele , Como Me Lele To Mele El Pilin  Que Te Saquen A Pasear Que Te Saquen A Bailar Que Te Saquen A Pasear Que Te Saquen A Bailar  Como Me Lele , Como Me Lele , Como Me Lele To Mele El Pilin </html>");
        AboutMe.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(AboutMe);
        AboutMe.setBounds(10, 530, 1090, 160);

        NameLabel.setBackground(new java.awt.Color(102, 102, 102));
        NameLabel.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("Juanito Banana");
        add(NameLabel);
        NameLabel.setBounds(320, 370, 750, 60);

        FriendCounterLabel.setBackground(new java.awt.Color(102, 102, 102));
        FriendCounterLabel.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        FriendCounterLabel.setForeground(new java.awt.Color(204, 204, 204));
        FriendCounterLabel.setText("#### amigos");
        add(FriendCounterLabel);
        FriendCounterLabel.setBounds(320, 430, 660, 30);

        PostsCounter.setBackground(new java.awt.Color(102, 102, 102));
        PostsCounter.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        PostsCounter.setForeground(new java.awt.Color(204, 204, 204));
        PostsCounter.setText("#### publicaciones");
        add(PostsCounter);
        PostsCounter.setBounds(320, 460, 660, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void EditProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileButtonActionPerformed
        this.EditProfile.pack();
        this.EditProfile.setAlwaysOnTop(true);
        this.EditProfile.setLocationRelativeTo(null);
        this.EditProfile.setVisible(true);
    }//GEN-LAST:event_EditProfileButtonActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        this.EditProfile.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void ConfirmChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmChangesActionPerformed
        // REALIZAR CÓDIGO PARA ACTUALIZAR DB
        BinaryDiary.refreshProfile();
        this.EditProfile.dispose();
    }//GEN-LAST:event_ConfirmChangesActionPerformed

    private void ProfilePictureEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilePictureEditMouseClicked
        // REALIZAR CÓDIGO DE FILECHOOSER
        // UTILIZAR ESTE METODO PARA RESIZE -> ProfilePictureEdit.setIcon(processImage(coverPhoto, 1160, 359));
    }//GEN-LAST:event_ProfilePictureEditMouseClicked

    private void ProfileBackgroundEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileBackgroundEditMouseClicked
        // REALIZAR CÓDIGO DE FILECHOOSER
        // UTILIZAR ESTE METODO PARA RESIZE -> ProfilePictureEdit.setIcon(processImage(coverPhoto, 1160, 359));
    }//GEN-LAST:event_ProfileBackgroundEditMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutMe;
    private javax.swing.JTextArea AboutMeEdit;
    private javax.swing.JButton ConfirmChanges;
    private javax.swing.JDialog EditProfile;
    private javax.swing.JButton EditProfileButton;
    private javax.swing.JPanel EditProfilePanel;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel FriendCounterLabel;
    private javax.swing.JLabel Label;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel PostsCounter;
    private javax.swing.JLabel ProfileBackground;
    private javax.swing.JLabel ProfileBackgroundEdit;
    private javax.swing.JLabel ProfilePicture;
    private javax.swing.JLabel ProfilePictureEdit;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
